---
jobs:
  build_all:
    executor:
      name: node/default
    steps:
      - checkout
      -
        node/with-cache:
          steps:
            -
              run: "npm install"
            -
              run: "npm test"
  dev_deploy:
    executor:
      name: node/default
    steps:
      - checkout
      -
        node/with-cache:
          steps:
            -
              run: "npm run build"
            -
              run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
  master_deploy:
    executor:
      name: node/default
      steps:
        - checkout
        - node/with-cache:
            steps:
              - run: "echo just deployed for master"
orbs:
  node: circleci/node@1.1.6
version: 2.1
workflows:
  build_all:
    jobs:
      - build_all:
          filters:
            branches:
              ignore:
                - development
                - master
  dev_workflow:
    jobs:
      - build_all
      - dev_deploy:
          filters:
            branches:
              only:
                - development
  prod_workflow:
    jobs:
      - build_all
      - master_deploy:
          filters:
            branches:
              only:
                - master
