---
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      -
        node/with-cache:
          steps:
            -
              run: "npm install"
            -
              run: "npm test"
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      -
        node/with-cache:
          steps:
            -
              run: "echo ran deploy"
orbs:
  node: circleci/node@1.1.6
version: 2.1
workflows:
  flux-pipeline:
    jobs:
      - build-and-test
      -
        deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build-and-test
