version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy-dev:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo ran deploy
workflows:
    flux-pipeline:
      jobs:
        - build-and-test
        - deploy-dev:
            requires
              - build-and-test
            filters:
              branches:
                only:
                  - develop
