---
jobs:
  build_all:
    executor:
      name: node/default
    steps:
      - checkout
      -
        node/with-cache:
          steps:
            -
              run: "npm install"
            -
              run: "npm test"
  dev_deploy:
    executor:
      name: node/default
    steps:
      - checkout
      -
        node/with-cache:
          steps:
            -
              run: "npm run build"
            -
              run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
  prod_deploy:
    executor:
      name: node/default
    steps:
      - checkout
      -
        node/with-cache:
          steps:
            -
              run: echo prod deploy

orbs:
  node: circleci/node@1.1.6
version: 2.1
workflows:
  build_workflow:
    jobs:
      - build_all:
          filters:
            branches:
              ignore:
                - develop
                - master
  dev_workflow:
    jobs:
      - build_all:
          filters:
            branches:
              only:
                - develop
      - hold:
          type:
            - approval
          requires:
            - build_all
          filters:
            branches:
              only:
                - develop
      - dev_deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - develop
  prod_workflow:
    jobs:
      - build_all:
          filters:
            branches:
              only:
                - master
      - hold:
          type:
            - approval
          requires:
            - build_all
          filters:
            branches:
              only:
                - master
      - prod_deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
